name: Build Next.JS

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/
      - run: yarn
      - run: yarn build
      - run: yarn export
      - name: Configure git identity
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Stage, commit & push changes
        run: |
          git add .
          git commit -m  "📝 docs: auto build triggered"
          git push origin main
